### PR TITLE
PP-50 Server config for tests

### PR DESCRIPTION
**Pull request by wilsoniovlabs**
This PR to use the server config file path from the new export function on rif relay server.

### CODE REVIEW

**Comment by mortelli** [comment]
Please make sure to point this PR to `develop` instead of `master` :pray:

**Comment by wilsoniovlabs** [comment]
The PR is pointed to develop.

**Comment by mortelli** [comment]
@wilsoniovlabs please take a look at the diff for this PR, it doesn't seem to be correct

**Review by mortelli — COMMENTED** [review]
thanks for this PR @wilsoniovlabs.

i see 2 issues here:

the first one is that the CI tests aren't passing. that's because this project is pointing to the `master` branch for the `rif-relay-server` repo, when it should in fact point to the `feature/PP-50/exporting-server-configuration` branch. you can change this in the dependencies to make sure that the tests pass, and then change it back once [the `rif-relay-server` PR](https://github.com/infuy/rif-relay-server/pull/5) is merged.

in addition to this, there seems to be an issue with the `dist/index.js` file in that branch:

https://github.com/infuy/rif-relay-server/blob/693db09d17e94328d709d4f238ec75cf9ff55d87/dist/index.js#L23-L25

is it possible that these lines were added manually? because when i re-compile the server from this branch, they are deleted.

it's important to know if this is the case, because i cannot seem to run the tests successfully when i update the `dist` for this branch on the server project.

**Review by mortelli — COMMENTED** [review]
thanks for the updates @wilsoniovlabs 

there's 2 issues here still:
1. the previously mentioned tests issue:
> the CI tests aren't passing. that's because this project is pointing to the master branch for the rif-relay-server repo, when it should in fact point to the feature/PP-50/exporting-server-configuration branch. you can change this in the dependencies to make sure that the tests pass, and then change it back once the rif-relay-server PR is merged.

make sure to verify this :mag: 

2. the implementation doesn't seem to be entirely working. you'll remember that the original issue stated:

> Relay servers are used when the integration tests are run. These make use of the server-config.json file from this dependency.
> 
> The problem with this is that it can clash if the tests are executed at the same time that a server is run separately (but using the same config file).
> 
> Let's create a test config file for the server dependency and use it in the integration tests repo.

however, when i start the server and in parallel run the tests, the following error comes up:
```
  1) Contract: KnownRelaysManager 2
       #refresh()
         "before all" hook for "should consider all relay managers with stake and authorization as active":
     Error: listen EADDRINUSE: address already in use :::8090
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at Function.listen (/home/rafa/github.com/rsksmart/rif-relay/node_modules/express/lib/application.js:618:24)
    at HttpServer.start (/home/rafa/github.com/rsksmart/rif-relay/node_modules/@rsksmart/rif-relay-server/src/HttpServer.ts:36:44)
    at run (/home/rafa/github.com/rsksmart/rif-relay/node_modules/@rsksmart/rif-relay-server/src/commands/Start.ts:91:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  Error: Error: listen EADDRINUSE: address already in use :::8090
      at Server.setupListenHandle [as _listen2] (net.js:1316:16)
      at listenInCluster (net.js:1364:12)
      at Server.listen (net.js:1450:7)
      at Function.listen (node_modules/express/lib/application.js:618:24)
      at HttpServer.start (node_modules/@rsksmart/rif-relay-server/src/HttpServer.ts:36:44)
      at run (node_modules/@rsksmart/rif-relay-server/src/commands/Start.ts:91:16)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at ChildProcess.doaListener (test/TestUtils.ts:109:24)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

which means both repos are using the same config file.

**Comment by mortelli** [comment]
@wilsoniovlabs 

sorry, could you please explain why you've removed the husky githooks in your [latest commit](https://github.com/rsksmart/rif-relay/commit/34261e67c53aae71599eb734a3ca8663c193a52b)?

i don't think this is correct; it's applied each time you commit changes to the repo. it's not unused afaik

**Comment by mortelli** [comment]
closed in favor of https://github.com/infuy/rif-relay-server/pull/5

**Pull request closed without merging**
